// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.DataAccess;

#nullable disable

namespace OnlineStore.DataAccess.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20230417133528_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(8920),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 1",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 197.943814690336m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(8948),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 1",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 122.806139303936m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(8979),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 2",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 87.9826435260168m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(8986),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 2",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 177.938595438653m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9016),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 3",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 142.709559623566m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9022),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 3",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 199.551727586247m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9050),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 4",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 103.451500665276m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9056),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 4",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 160.239314697244m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9084),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 5",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 23.5596236145376m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9090),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 5",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 177.146514575256m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9116),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 6",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 99.0925097454869m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9122),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 6",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 235.452422832959m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9261),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 7",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 155.67458978636m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9267),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 7",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 124.577748343943m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9293),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 8",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 34.4776874063506m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9298),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 8",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 39.2454725073773m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9325),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 9",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 198.479698559333m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9331),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 9",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 140.493437346835m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9358),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 10",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 44.6122586608008m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9364),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 10",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 202.011190316824m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9391),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 11",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 211.089611254976m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9397),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 11",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 86.0234051662821m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9421),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 12",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 226.23493521835m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9427),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 12",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 65.4891405250716m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9454),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 13",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 171.977971235181m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9460),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 13",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 123.943939714192m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9484),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 14",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 131.26129956166m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9490),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 14",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 212.9139504308m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9517),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 15",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 20.1915342625744m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9523),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 15",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 145.417045376529m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9547),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 16",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 168.654211735008m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9553),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 16",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 115.458207062096m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9580),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 17",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 190.484411164399m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9585),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 17",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 183.446026784899m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9612),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 18",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 209.97307048257m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9665),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 18",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 97.4165536695294m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9694),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 19",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 186.808155066922m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9700),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 19",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 232.002777711255m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9724),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 20",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 96.3239702582256m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9730),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 20",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 84.5307566797162m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9757),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 21",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 123.986300538768m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9763),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 21",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 102.163259176565m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9786),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 22",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 108.190701277961m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9792),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 22",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 102.876163985139m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9819),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 23",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 81.899055651364m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9825),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 23",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 131.331129156638m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9849),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 24",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 134.505413297666m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9855),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 24",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 85.0041968412638m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9882),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Camera Product 25",
                            Thumbnail = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            UnitPrice = 128.664638158353m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 17, 20, 35, 28, 673, DateTimeKind.Local).AddTicks(9888),
                            CreatedById = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            IsDeleted = false,
                            Name = "Shoe 25",
                            Thumbnail = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80\r\n",
                            UnitPrice = 73.4944285572363m
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Camera equipment",
                            Image = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
                            IsDeleted = false,
                            Name = "Camera"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Shoes",
                            Image = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
                            IsDeleted = false,
                            Name = "Footwear"
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CivilianId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CivilianId = "123abc",
                            DateOfBirth = new DateTime(1998, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FirstName = "Anthony",
                            IsDeleted = false,
                            LastName = "von Schieszl",
                            Password = "123",
                            PhoneNumber = "12345678",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CivilianId = "123cba",
                            DateOfBirth = new DateTime(1993, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clerk@example.com",
                            FirstName = "Bob",
                            IsDeleted = false,
                            LastName = "B.",
                            Password = "123",
                            PhoneNumber = "22345678",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            CivilianId = "321abc",
                            DateOfBirth = new DateTime(1987, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@example.com",
                            FirstName = "Carol",
                            IsDeleted = false,
                            LastName = "C.",
                            Password = "123",
                            PhoneNumber = "32345678",
                            Role = 3
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("OnlineStore.Domain.Entities.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });
#pragma warning restore 612, 618
        }
    }
}
